name: Replace GA Secret
on:
  push:
    branches: [ main ]
    
permissions:
  contents: write  # This is crucial for pushing to gh-pages

jobs:
  replace-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for deployment

      - name: Replace GA placeholder
        run: |
          sed -i "s/WOW_A_SECRET_PLACEHOLDER/${{ secrets.WOW_A_SECRET }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
